# DecodeLabs Data Cleaning & Preparation Project

## Introduction

This project focuses on data cleaning, preparation, and validation using Python and Pandas. The objective is to identify data quality issues such as missing values, duplicates, formatting inconsistencies, and validation errors while preparing the dataset for analysis.

The dataset contains customer order transaction records including product information, pricing, payment methods, and order status details.

# Data Loading

The dataset was imported from an Excel file into Python using the Pandas library for cleaning and validation.

In [ ]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel(r"C:\Users\REAL TIME\Documents\Dataset for Data Analytics.xlsx")

# Dataset Familiarization

Initial exploration was performed to understand the dataset structure, identify data types, and inspect sample records.

In [5]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [6]:
df.shape

(1200, 14)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

# Missing Value Analysis

The dataset was checked for missing values to identify incomplete records and determine appropriate cleaning strategies.

In [8]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

### Result

All missing values in the `CouponCode` column were successfully replaced with **"No Coupon"**.

This ensured that the dataset remained complete and ready for further analysis without introducing ambiguity regarding coupon usage.

In [29]:
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

In [30]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
CalculatedTotal    0
dtype: int64

# Duplicate Record Validation

The dataset was checked for duplicate rows and duplicate Order IDs to ensure data integrity and uniqueness.

In [9]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['OrderID'].duplicated().sum()

np.int64(0)

# Date Format Validation

The Date column was validated to ensure consistent formatting and proper datetime conversion for accurate processing and analysis.

In [12]:
df['Date'].head()

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
Name: Date, dtype: datetime64[ns]

# Invalid Value Validation

Validation checks were performed to identify negative values and incorrect calculations within the dataset.

In [13]:
df[df['Quantity'] < 0]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

In [14]:
df[df['UnitPrice'] < 0]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

In [15]:
df[df['TotalPrice'] < 0]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

# Total Price Validation

The TotalPrice column was validated by comparing it against Quantity × UnitPrice calculations.

In [17]:
(df['Quantity'] * df['UnitPrice']) == df['TotalPrice']

0        True
1        True
2       False
3        True
4        True
        ...
1195     True
1196     True
1197     True
1198     True
1199     True
Length: 1200, dtype: bool

In [18]:
((df['Quantity'] * df['UnitPrice']) != df['TotalPrice']).sum()

np.int64(107)

In [19]:
invalid_totals = df[
    (df['Quantity'] * df['UnitPrice']) != df['TotalPrice']
]

invalid_totals.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
10,ORD200010,2023-12-29,C43443,Tablet,5,625.97,333 Main St,Credit Card,Returned,TRK98859248,9,WINTER15,Instagram,3129.85
11,ORD200011,2024-02-17,C93861,Monitor,3,49.14,831 Main St,Online,Returned,TRK48234646,7,SAVE10,Email,147.42
32,ORD200032,2023-05-01,C12388,Tablet,5,536.72,830 Main St,Cash,Delivered,TRK99261395,10,NaN,Email,2683.60
41,ORD200041,2023-12-05,C20212,Monitor,3,611.45,657 Main St,Gift Card,Pending,TRK69733327,4,FREESHIP,Instagram,1834.35

In [20]:
invalid_totals.shape

(107, 14)

In [21]:
df['CalculatedTotal'] = df['Quantity'] * df['UnitPrice']

In [22]:
df[['Quantity', 'UnitPrice', 'TotalPrice', 'CalculatedTotal']].head(10)

   Quantity  UnitPrice  TotalPrice  CalculatedTotal
0         5     570.62     2853.10          2853.10
1         2     151.35      302.70           302.70
2         5     550.68     2753.40          2753.40
3         1     273.19      273.19           273.19
4         4     626.01     2504.04          2504.04
5         2     245.86      491.72           491.72
6         1     664.42      664.42           664.42
7         5     149.55      747.75           747.75
8         2     134.28      268.56           268.56
9         4     509.38     2037.52          2037.52

In [23]:
(
    round(df['Quantity'] * df['UnitPrice'], 2)
    != round(df['TotalPrice'], 2)
).sum()

np.int64(0)

Initial validation checks suggested inconsistencies between Quantity × UnitPrice and TotalPrice values. However, after applying currency rounding to two decimal places, all calculations were confirmed to be accurate. The discrepancy was caused by floating-point precision behavior in Python.

# Text Standardization

Text fields were standardized to improve consistency and readability across the dataset.

In [32]:
text_columns = [
    'Product',
    'PaymentMethod',
    'OrderStatus',
    'CouponCode',
    'ReferralSource'
]

for col in text_columns:
    df[col] = df[col].str.title()

In [33]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,CalculatedTotal
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,Save10,Instagram,2853.10,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,Save10,Referral,302.70,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,Freeship,Email,2753.40,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,Save10,Facebook,273.19,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,Save10,Email,2504.04,2504.04

# Validation Summary

The following validation results were confirmed:

- No duplicate rows were found
- No duplicate Order IDs were detected
- No negative values existed in Quantity, UnitPrice, or TotalPrice
- Date formatting was consistent and valid
- TotalPrice calculations were verified successfully after rounding validation
- Missing CouponCode values were handled appropriately

# Exporting Cleaned Dataset

The cleaned and validated dataset was exported for future analysis and reporting.

In [34]:
df.to_excel("cleaned_dataset.xlsx", index=False)

# Conclusion

This project demonstrated the importance of data cleaning and validation in preparing reliable datasets for analysis. Several quality checks were performed including missing value handling, duplicate validation, date verification, and financial calculation validation to ensure dataset integrity and consistency.